import { useEffect, useMemo, useState } from "react";

export const COPY = {
  goblin: {
    toggle: "Serious Mode",
    landing: {
      badge: "Planning for charming chaos",
      hero: "Find a time the whole cave will actually keep.",
      subhero: "Share one beautiful link, gather calm little yeses and maybes, and pick a time without turning the group chat into soup.",
      cta: "Start a Hangout",
      howTitle: "A softer ritual",
      howDescription: "Set the shape of the plan, pass the link around, and let the best window rise to the top.",
      howSteps: [
        "No accounts, no signup, no dramatic spreadsheet detours.",
        "Weighted votes: yes, maybe, snack-bribable, and no.",
        "Calendar export when the cave agrees on a winner.",
      ],
    },
    create: {
      title: "Plan a Hangout",
      subtitle: "Shape the window, set the vibe, and we will forge the links for you.",
      fieldTitle: "Quest Name",
      fieldTitlePlaceholder: "e.g. Lair cleanup, Snack heist, Mandatory fun",
      fieldDescription: "Battle Plan",
      fieldDescriptionPlaceholder: "Describe the scheme (optional)",
      fieldTimezone: "Time Dimension",
      fieldDuration: "Duration of Chaos",
      fieldSlotSize: "Slot size",
      fieldStartDate: "Earliest day",
      fieldEndDate: "Latest day",
      fieldDailyStart: "Dawn patrol",
      fieldDailyEnd: "Lights out",
      submitButton: "Forge the Links",
      submitLoading: "Forging...",
      shareTitle: "Share panel",
      shareEmpty: "Create an event to reveal the public and host links.",
      sharePublicLabel: "Public quest link",
      shareHostLabel: "Host throne link",
    },
    event: {
      loading: "Waking up the goblins...",
      noDescription: "The host left no instructions. Suspicious.",
      viewResults: "Spy on results",
      finalizedTitle: "Chosen time",
      downloadCal: "Add to goblin calendar",
      joinTitle: "Join the plan",
      joinPlaceholder: "Your goblin name",
      joinButton: "Join event",
      joinedStatus: "You are in. The horde is delighted.",
      availTitle: "Mark your availability",
      availCount: "{count} slots claimed",
      saveButton: "Save availability",
      savedStatus: "Availability etched in stone.",
    },
    results: {
      loading: "Crunching goblin math...",
      title: "Best windows for the horde",
      participantCount: "{count} goblins in the scoring pile.",
      rankLabel: "Rank",
      percentLabel: "of max",
      scoreLabel: "Score",
      canAttendLabel: "Can make it",
      cannotAttendLabel: "Can't make it",
      nobodyYet: "Nobody yet",
      nobody: "Nobody",
    },
    host: {
      loading: "Entering the throne room...",
      title: "Host studio",
      eventLabel: "Quest",
      percentLabel: "of max score",
      finalizeButton: "Choose this time",
      finalizedTitle: "Final selection",
      downloadIcs: "Download royal scroll (.ics)",
    },
    error: {
      title: "A goblin tripped over the wires",
      description: "Something broke and it is probably Gary's fault.",
      homeButton: "Retreat to the cave",
    },
    availability: {
      yes: "Absolutely",
      maybe: "Meh, possibly",
      bribe: "If bribed with snacks",
      no: "Over my cold goblin body",
    },
    grid: {
      markEvenings: "Claim all evenings",
      clear: "Scorched earth",
    },
  },
  serious: {
    toggle: "Goblin Mode",
    landing: {
      badge: "Thoughtful group availability",
      hero: "Settle on a time without the coordination spiral.",
      subhero: "Create a beautiful event page, collect everyone's availability, and lock a time with zero accounts required.",
      cta: "Create an Event",
      howTitle: "How it works",
      howDescription: "Set the shape of the event and we will turn it into a shareable planning flow.",
      howSteps: [
        "No accounts required.",
        "Weighted votes for yes, maybe, if needed, and no.",
        "ICS download after finalizing.",
      ],
    },
    create: {
      title: "Create an Event",
      subtitle: "Define the window, share the page, and let the best time emerge.",
      fieldTitle: "Title",
      fieldTitlePlaceholder: "e.g. Team standup, Book club, Game night",
      fieldDescription: "Description",
      fieldDescriptionPlaceholder: "Add details (optional)",
      fieldTimezone: "Timezone",
      fieldDuration: "Duration",
      fieldSlotSize: "Slot size",
      fieldStartDate: "Start date",
      fieldEndDate: "End date",
      fieldDailyStart: "Daily start",
      fieldDailyEnd: "Daily end",
      submitButton: "Create Event",
      submitLoading: "Creating...",
      shareTitle: "Share Links",
      shareEmpty: "Create an event to get a public link and a private host finalize link.",
      sharePublicLabel: "Public event",
      shareHostLabel: "Host link",
    },
    event: {
      loading: "Loading event...",
      noDescription: "No description provided.",
      viewResults: "View results",
      finalizedTitle: "Finalized time",
      downloadCal: "Download calendar file",
      joinTitle: "Join This Event",
      joinPlaceholder: "Display name",
      joinButton: "Join Event",
      joinedStatus: "Successfully joined.",
      availTitle: "Mark Your Availability",
      availCount: "{count} slots marked",
      saveButton: "Save Availability",
      savedStatus: "Availability saved.",
    },
    results: {
      loading: "Calculating results...",
      title: "Top recommended times",
      participantCount: "{count} participants in the scoring pile.",
      rankLabel: "Rank",
      percentLabel: "of max",
      scoreLabel: "Score",
      canAttendLabel: "Can make it",
      cannotAttendLabel: "Can't make it",
      nobodyYet: "Nobody yet",
      nobody: "Nobody",
    },
    host: {
      loading: "Loading host control panel...",
      title: "Host studio",
      eventLabel: "Event",
      percentLabel: "of max score",
      finalizeButton: "Finalize This Time",
      finalizedTitle: "Finalized",
      downloadIcs: "Download ICS",
    },
    error: {
      title: "Something went wrong",
      description: "An unexpected error occurred. Please try again.",
      homeButton: "Go back home",
    },
    availability: {
      yes: "Yes",
      maybe: "Maybe",
      bribe: "If needed",
      no: "No",
    },
    grid: {
      markEvenings: "Mark all evenings",
      clear: "Clear",
    },
  },
};

export function useMode() {
  const [mode, setMode] = useState(() => localStorage.getItem("mode") || "goblin");

  useEffect(() => {
    localStorage.setItem("mode", mode);
  }, [mode]);

  const copy = useMemo(() => COPY[mode], [mode]);

  return {
    mode,
    copy,
    toggleMode: () => setMode((current) => (current === "goblin" ? "serious" : "goblin")),
  };
}
