import { useEffect, useMemo, useState } from "react";

export const COPY = {
  serious: {
    toggle: "Goblin Mode",
    landing: {
      badge: "Premium scheduling for real plans",
      hero: "Make the scheduling link feel as polished as the event.",
      subhero:
        "Create a calm, premium planning page for dinners, clubs, workshops, and lightweight team rituals. Collect responses, surface the best windows, and lock a time without making people create accounts.",
      cta: "Create an Event",
      howTitle: "How It Works",
      howDescription: "Set the window once, share the link, and let the best option rise to the top without spreadsheet cleanup.",
      howSteps: [
        "Hosts configure the date range, duration, and daily hours in a few fields.",
        "Guests respond from one shared page with no accounts or logins.",
        "Hosts review ranked windows, finalize once, and export the winner to calendar.",
      ],
    },
    create: {
      title: "Create a Scheduling Page",
      subtitle: "Set the shape of the plan and ship a clean share link in under a minute.",
      fieldTitle: "Title",
      fieldTitlePlaceholder: "e.g. Book club, Team retro, Client workshop",
      fieldDescription: "Description",
      fieldDescriptionPlaceholder: "Context, location, or agenda notes",
      fieldTimezone: "Timezone",
      fieldDuration: "Duration",
      fieldSlotSize: "Slot size",
      fieldStartDate: "Start date",
      fieldEndDate: "End date",
      fieldDailyStart: "Daily start",
      fieldDailyEnd: "Daily end",
      submitButton: "Create Event",
      submitLoading: "Creating...",
      shareTitle: "Share Links",
      shareEmpty: "Create an event to reveal the public response page and private host workspace.",
      sharePublicLabel: "Public event page",
      shareHostLabel: "Host workspace",
    },
    event: {
      loading: "Loading event...",
      noDescription: "No description provided.",
      viewResults: "View ranking",
      finalizedTitle: "Finalized time",
      downloadCal: "Download calendar file",
      joinTitle: "Join this event",
      joinPlaceholder: "Your name",
      joinButton: "Join event",
      joinedStatus: "You are in. Your schedule is ready to fill out.",
      sessionExpired: "We could not find your previous response token. Join again to keep editing.",
      availTitle: "Mark availability",
      availCount: "{count} time blocks marked",
      saveButton: "Save response",
      savedStatus: "Your response is saved.",
      clearedStatus: "Your saved response is now empty.",
    },
    results: {
      loading: "Calculating recommendations...",
      title: "Top recommended times",
      participantCount: "{count} invited participants in scoring.",
      rankLabel: "Rank",
      percentLabel: "of max score",
      scoreLabel: "Score",
      canAttendLabel: "Strongly available",
      cannotAttendLabel: "Needs compromise",
      nobodyYet: "Nobody yet",
      nobody: "Nobody",
    },
    host: {
      loading: "Loading host workspace...",
      title: "Host workspace",
      eventLabel: "Event",
      percentLabel: "of max score",
      finalizeButton: "Finalize this time",
      finalizedTitle: "Locked schedule",
      downloadIcs: "Download calendar file",
    },
    error: {
      title: "Something went wrong",
      description: "An unexpected error interrupted the page. Refresh and try again.",
      homeButton: "Back to home",
    },
    availability: {
      yes: "Works well",
      maybe: "Can flex",
      bribe: "Possible with effort",
      no: "Unavailable",
    },
    grid: {
      markEvenings: "Mark evenings",
      clear: "Clear schedule",
      restore: "Restore saved",
    },
  },
  goblin: {
    toggle: "Calm Mode",
    landing: {
      badge: "Optional goblin energy",
      hero: "Find a time the whole cave will actually keep.",
      subhero:
        "The same reliable scheduling engine, just with extra moss. Share one link, collect the cave's availability, and choose a winner without letting the group chat ferment.",
      cta: "Start a Hangout",
      howTitle: "Gentle Goblin Math",
      howDescription: "Set the window, toss the link into the chat, and let the best option claw its way to the top.",
      howSteps: [
        "No accounts, no solemn spreadsheets, no ceremonial setup.",
        "Guests answer with yes, maybe, snack-powered, or no.",
        "The host crowns a winner once and ships the calendar file.",
      ],
    },
    create: {
      title: "Forge a Planning Page",
      subtitle: "Set the time window, send the cave a link, and let the logistics sort themselves out.",
      fieldTitle: "Quest name",
      fieldTitlePlaceholder: "e.g. Snack summit, Board game raid, Cave cleanup",
      fieldDescription: "Battle plan",
      fieldDescriptionPlaceholder: "Context for the horde",
      fieldTimezone: "Time dimension",
      fieldDuration: "Duration of chaos",
      fieldSlotSize: "Slot size",
      fieldStartDate: "Earliest day",
      fieldEndDate: "Latest day",
      fieldDailyStart: "Dawn patrol",
      fieldDailyEnd: "Lights out",
      submitButton: "Forge the links",
      submitLoading: "Forging...",
      shareTitle: "Share panel",
      shareEmpty: "Create a quest to reveal the public cave page and private throne room.",
      sharePublicLabel: "Public quest page",
      shareHostLabel: "Host throne room",
    },
    event: {
      loading: "Waking up the goblins...",
      noDescription: "The host left no instructions. Bold.",
      viewResults: "Peek at the ranking",
      finalizedTitle: "Chosen time",
      downloadCal: "Download goblin calendar",
      joinTitle: "Join the quest",
      joinPlaceholder: "Your goblin name",
      joinButton: "Join event",
      joinedStatus: "You are in. The cave awaits your markings.",
      sessionExpired: "Your old cave token vanished. Join again to keep editing.",
      availTitle: "Mark availability",
      availCount: "{count} cave blocks marked",
      saveButton: "Save response",
      savedStatus: "Your response is etched into the cave wall.",
      clearedStatus: "The wall is clear again.",
    },
    results: {
      loading: "Crunching goblin math...",
      title: "Best windows for the horde",
      participantCount: "{count} goblins in scoring.",
      rankLabel: "Rank",
      percentLabel: "of max score",
      scoreLabel: "Score",
      canAttendLabel: "Ready to scamper",
      cannotAttendLabel: "Would grumble",
      nobodyYet: "Nobody yet",
      nobody: "Nobody",
    },
    host: {
      loading: "Entering the throne room...",
      title: "Throne room",
      eventLabel: "Quest",
      percentLabel: "of max score",
      finalizeButton: "Crown this time",
      finalizedTitle: "Locked decree",
      downloadIcs: "Download royal scroll",
    },
    error: {
      title: "A goblin tripped over the wires",
      description: "Something broke and the mossy machinery needs a moment.",
      homeButton: "Retreat to the cave",
    },
    availability: {
      yes: "Absolutely",
      maybe: "Probably",
      bribe: "If snacks appear",
      no: "Absolutely not",
    },
    grid: {
      markEvenings: "Claim evenings",
      clear: "Scorched earth",
      restore: "Restore last etching",
    },
  },
};

export function useMode() {
  const [mode, setMode] = useState(() => localStorage.getItem("mode") || "serious");

  useEffect(() => {
    localStorage.setItem("mode", mode);
  }, [mode]);

  const copy = useMemo(() => COPY[mode], [mode]);

  return {
    mode,
    copy,
    toggleMode: () => setMode((current) => (current === "goblin" ? "serious" : "goblin")),
  };
}
