import { useEffect, useMemo, useState } from "react";

export const COPY = {
  goblin: {
    toggle: "Switch to Serious Mode",
    landing: {
      badge: "Cave-certified scheduling sorcery",
      hero: "Convince the whole cave to hang out at the same time.",
      subhero: "Summon a scheduling link, collect snack-bribed maybes, and crown a winning timeslot.",
      cta: "Start the Shenanigans",
      howTitle: "The Sacred Ritual",
      howDescription: "Forge a quest, fling the link into the group chat, harvest availability confessions, and crown a winner.",
      howSteps: [
        "No accounts, no signup, no blood oaths.",
        "Weighted votes: yes, maybe, snack-bribable, and hard no.",
        "ICS download so it actually lands on your calendar.",
      ],
    },
    create: {
      title: "Summon a Hangout",
      subtitle: "Name your quest and the goblins will forge a link of great power.",
      fieldTitle: "Quest Name",
      fieldTitlePlaceholder: "e.g. Lair cleanup, Snack heist, Mandatory fun",
      fieldDescription: "Battle Plan",
      fieldDescriptionPlaceholder: "Describe the scheme (optional)",
      fieldTimezone: "Time Dimension",
      fieldDuration: "Duration of Chaos",
      fieldSlotSize: "Slot size",
      fieldStartDate: "Earliest day",
      fieldEndDate: "Latest day",
      fieldDailyStart: "Dawn patrol",
      fieldDailyEnd: "Lights out",
      submitButton: "Forge the Link",
      submitLoading: "Summoning...",
      shareTitle: "Scroll of Links",
      shareEmpty: "Forge an event to receive your sacred links.",
      sharePublicLabel: "Public quest link",
      shareHostLabel: "Host throne link",
    },
    event: {
      loading: "Waking up the goblins...",
      noDescription: "The host left no instructions. Suspicious.",
      viewResults: "Spy on results",
      finalizedTitle: "The Decree",
      downloadCal: "Add to goblin calendar",
      joinTitle: "Pledge Your Attendance",
      joinPlaceholder: "Your goblin name",
      joinButton: "Swear fealty and join",
      joinedStatus: "Fealty sworn. Welcome to the horde.",
      availTitle: "Mark Your Availability",
      availCount: "{count} slots claimed",
      saveButton: "Lock it in",
      savedStatus: "Availability etched in stone.",
    },
    results: {
      loading: "Crunching goblin math (several goblins were harmed)...",
      title: "The Goblin Leaderboard",
      participantCount: "{count} goblins in the scoring pile.",
      rankLabel: "Rank",
      percentLabel: "of max",
      scoreLabel: "Score",
      canAttendLabel: "Can make it",
      cannotAttendLabel: "Can't make it",
      nobodyYet: "Nobody yet",
      nobody: "Nobody",
    },
    host: {
      loading: "Entering the throne room...",
      title: "The Throne Room",
      eventLabel: "Quest",
      percentLabel: "of max score",
      finalizeButton: "Decree This Time",
      finalizedTitle: "The Royal Decree",
      downloadIcs: "Download royal scroll (.ics)",
    },
    error: {
      title: "A goblin tripped over the wires",
      description: "Something broke and it's probably Gary's fault.",
      homeButton: "Retreat to the cave",
    },
    availability: {
      yes: "Absolutely",
      maybe: "Meh, possibly",
      bribe: "If bribed with snacks",
      no: "Over my cold goblin body",
    },
    grid: {
      markEvenings: "Claim all evenings",
      clear: "Scorched earth",
    },
  },
  serious: {
    toggle: "Switch to Goblin Mode",
    landing: {
      badge: "Group availability scheduler",
      hero: "Find the best time without the coordination mess.",
      subhero: "Create an event, collect availability, and lock a time with no accounts required.",
      cta: "Create a Hangout",
      howTitle: "How it works",
      howDescription: "Set up the details and we'll generate a shareable link.",
      howSteps: [
        "No accounts required.",
        "Weighted votes for yes, maybe, if needed, and no.",
        "ICS download after finalizing.",
      ],
    },
    create: {
      title: "Create an Event",
      subtitle: "Set up the details and we'll generate a shareable link.",
      fieldTitle: "Title",
      fieldTitlePlaceholder: "e.g. Team standup, Book club, Game night",
      fieldDescription: "Description",
      fieldDescriptionPlaceholder: "Add details (optional)",
      fieldTimezone: "Timezone",
      fieldDuration: "Duration",
      fieldSlotSize: "Slot size",
      fieldStartDate: "Start date",
      fieldEndDate: "End date",
      fieldDailyStart: "Daily start",
      fieldDailyEnd: "Daily end",
      submitButton: "Create Event",
      submitLoading: "Creating...",
      shareTitle: "Share Links",
      shareEmpty: "Create an event to get a public link and a private host finalize link.",
      sharePublicLabel: "Public event",
      shareHostLabel: "Host link",
    },
    event: {
      loading: "Loading event...",
      noDescription: "No description provided.",
      viewResults: "View results",
      finalizedTitle: "Finalized Time",
      downloadCal: "Download calendar file",
      joinTitle: "Join This Event",
      joinPlaceholder: "Display name",
      joinButton: "Join Event",
      joinedStatus: "Successfully joined.",
      availTitle: "Mark Your Availability",
      availCount: "{count} slots marked",
      saveButton: "Save Availability",
      savedStatus: "Availability saved.",
    },
    results: {
      loading: "Calculating results...",
      title: "Top Recommended Times",
      participantCount: "{count} participants in the scoring pile.",
      rankLabel: "Rank",
      percentLabel: "of max",
      scoreLabel: "Score",
      canAttendLabel: "Can make it",
      cannotAttendLabel: "Can't make it",
      nobodyYet: "Nobody yet",
      nobody: "Nobody",
    },
    host: {
      loading: "Loading host control panel...",
      title: "Host Control Panel",
      eventLabel: "Event",
      percentLabel: "of max score",
      finalizeButton: "Finalize This Time",
      finalizedTitle: "Finalized",
      downloadIcs: "Download ICS",
    },
    error: {
      title: "Something went wrong",
      description: "An unexpected error occurred. Please try again.",
      homeButton: "Go back home",
    },
    availability: {
      yes: "Yes",
      maybe: "Maybe",
      bribe: "If needed",
      no: "No",
    },
    grid: {
      markEvenings: "Mark all evenings",
      clear: "Clear",
    },
  },
};

export function useMode() {
  const [mode, setMode] = useState(() => localStorage.getItem("mode") || "goblin");

  useEffect(() => {
    localStorage.setItem("mode", mode);
  }, [mode]);

  const copy = useMemo(() => COPY[mode], [mode]);

  return {
    mode,
    copy,
    toggleMode: () => setMode((current) => (current === "goblin" ? "serious" : "goblin")),
  };
}
